language: ruby
rvm:
  - 2.0.0
  - 2.1.2
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS="--2.0"
    - rvm: jruby-head
      env: JRUBY_OPTS="--2.1"
before_install:
  - gem install minitest -v '4.7.5' --no-document --quiet
